[build]
  ignore = "git diff --quiet HEAD^ HEAD src public index.html"
  publish = "dist"
  command = "yarn run build"

[build.environment]
  NODE_VERSION = "12"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
